# Generated by Django 4.2.1 on 2023-06-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_slug_alter_article_slug_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft')], default='draft', max_length=10, verbose_name='Status'),
        ),
    ]
